### ISSUE TITLE
Statusline/StatuslineNC unreadable

### ISSUE THREAD

**Issue by luetage** [Yazeed1s/minimal.nvim#1] opened 2022-07-17 08:32 UTC
Nice theme. I know most people run some statusline plugin, but for those who don’t it might be a good idea to set different highlights for foreground and background color of statusline and change it up for the inactive statusline additionally.

**Comment by strash** [comment] 2022-07-17 12:14
yep
```
StatusLine     xxx cterm=bold,reverse gui=bold,reverse guifg=#16181D guibg=#16181D
StatusLineNC   xxx cterm=reverse gui=reverse guifg=#16181D guibg=#16181D
```

**Comment by yazeed1s** [comment] 2022-07-17 14:36
> Nice theme. I know most people run some statusline plugin, but for those who don’t it might be a good idea to set different highlights for foreground and background color of statusline and change it up for the inactive statusline additionally.

Thanks! would you please provide a picture of how it should look without statusline plugins?

**Comment by Yazeed1s** [comment] 2022-07-17 14:37
> yep
> 
> ```
> StatusLine     xxx cterm=bold,reverse gui=bold,reverse guifg=#16181D guibg=#16181D
> StatusLineNC   xxx cterm=reverse gui=reverse guifg=#16181D guibg=#16181D
> ```

Thanks! will try that later today.

**Comment by luetage** [comment] 2022-07-17 14:45
> > Nice theme. I know most people run some statusline plugin, but for those who don’t it might be a good idea to set different highlights for foreground and background color of statusline and change it up for the inactive statusline additionally.
> 
> Thanks! would you please provide a picture of how it should look without statusline plugins?

I don’t know how it should look. It’s your theme ^^ Currently the text is invisible, see excerpt of highlights provided by strash.

**Comment by yazeed1s** [comment] 2022-07-17 16:04
> > > Nice theme. I know most people run some statusline plugin, but for those who don’t it might be a good idea to set different highlights for foreground and background color of statusline and change it up for the inactive statusline additionally.
> > 
> > 
> > Thanks! would you please provide a picture of how it should look without statusline plugins?
> 
> I don’t know how it should look. It’s your theme ^^ Currently the text is invisible, see excerpt of highlights provided by strash.

Np. I tried to set statusline to both "none" & "default"  so I can reproduce the "unreadable" issue, but nothing appears to be unreadable. if you can provide a screenshot of how it looks now so I can fix it.  Also, what nvim distro are you using?

**Comment by miguelaht** [comment] 2022-07-17 16:25
this it what it looks like on my side.

## Minimal
![Screen Shot 2022-07-17 at 10 22 25](https://user-images.githubusercontent.com/61668895/179411311-69159e3a-ed51-4f36-869e-74314f91c030.jpg)

## Minimal base16
![Screen Shot 2022-07-17 at 10 22 14](https://user-images.githubusercontent.com/61668895/179411326-73376f70-f44b-4a1e-b485-f024ea67184e.jpg)

**Comment by luetage** [comment] 2022-07-17 16:32
> Np. I tried to set statusline to both "none" & "default" so I can reproduce the "unreadable" issue, but nothing appears to be unreadable. if you can provide a screenshot of how it looks now so I can fix it. Also, what nvim distro are you using?

I’m not on any distro and I don’t use a statusline plugin. Use the ex command `highlight` to bring up the highlights. Pretty much at top are the highlights for StatusLine and StatusLineNC. In the case of your theme the background is the same as the foreground. You might have to disable your own statusline plugin/nvim distribution to see unaltered results.

**Comment by strash** [comment] 2022-07-17 17:00
@Yazeed1s The problem is that both `guifg=#16181D` and `guibg=#16181D` have the same color. You just need to change the foreground color to something else.

## `:highlight`
<img width="695" alt="Screen Shot 2022-07-17 at 19 48 23" src="https://user-images.githubusercontent.com/14233263/179416148-326f1197-5b6d-4867-bea3-72ba06813a6e.png">

## this is how it looks
<img width="1040" alt="Screen Shot 2022-07-17 at 19 56 40" src="https://user-images.githubusercontent.com/14233263/179416485-b35bbfd4-74b2-4cfb-a480-5b40a616b43a.png">

## this is how it should look
<img width="1039" alt="Screen Shot 2022-07-17 at 19 57 00" src="https://user-images.githubusercontent.com/14233263/179416535-f7873659-aac9-4a11-95cd-0099539c966f.png">

**Comment by yazeed1s** [comment] 2022-07-17 17:05
> > Np. I tried to set statusline to both "none" & "default" so I can reproduce the "unreadable" issue, but nothing appears to be unreadable. if you can provide a screenshot of how it looks now so I can fix it. Also, what nvim distro are you using?
> 
> 
> 
> I’m not on any distro and I don’t use a statusline plugin. Use the ex command `highlight` to bring up the highlights. Pretty much at top are the highlights for StatusLine and StatusLineNC. In the case of your theme the background is the same as the foreground. You might have to disable your own statusline plugin/nvim distribution to see unaltered results.
> 
> 

Okay thanks. yes i found that both foreground and background were set to color.balck, I fixed them, but i am not sure if the problem will be resolved in pure neovim or not. I will install and test the theme in pure noevim and other distros just to make sure everything is fine.

**Comment by yazeed1s** [comment] 2022-07-17 17:07
> @Yazeed1s The problem is that both `guifg=#16181D` and `guibg=#16181D` have the same color. You just need to change the foreground color to something else.
> 
> 
> 
> ## `:highlight`
> 
> <img width="695" alt="Screen Shot 2022-07-17 at 19 48 23" src="https://user-images.githubusercontent.com/14233263/179416148-326f1197-5b6d-4867-bea3-72ba06813a6e.png">
> 
> 
> 
> ## this is how it looks
> 
> <img width="1040" alt="Screen Shot 2022-07-17 at 19 56 40" src="https://user-images.githubusercontent.com/14233263/179416485-b35bbfd4-74b2-4cfb-a480-5b40a616b43a.png">
> 
> 
> 
> ## this is how it should look
> 
> <img width="1039" alt="Screen Shot 2022-07-17 at 19 57 00" src="https://user-images.githubusercontent.com/14233263/179416535-f7873659-aac9-4a11-95cd-0099539c966f.png">
> 
> 

You are right, both colors were set to colors.black. I already fixed them but i am going to test the theme in other distros then push all changes to upstream.

**Comment by yazeed1s** [comment] 2022-07-17 19:13
@luetage @luetage @strash 
It's fixed now, please go ahead and update the plugin.

**Closed as completed by yazeed1s** 2022-07-17 19:13 UTC
